server:
  port: 9191
 
spring:
  application:
    name: api-getway
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**

    config:
      enabled: true
      uri: http://localhost:9296

     
      